version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Disable Cloud SDK repository
          command: |
            sudo sed -i '/cloud-sdk-buster/s/^deb/#deb/' /etc/apt/sources.list.d/google-cloud-sdk.list
      - run:
          name: Update package lists and install Java 21
          command: |
            sudo apt-get update
            sudo apt-get install -y openjdk-11-jdk
            sudo apt-get install -y openjdk-21-jdk
      - run:
          name: Set Java 21 as default
          command: sudo update-java-alternatives -s java-21-openjdk
      - run:
          name: Check Java Version
          command: java -version
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: artifact-file
