version: 2.1

executors:
  java17:
    docker:
      - image: 'cimg/openjdk:17.0'

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    executor: java17
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Set up Android SDK
          command: |
            mkdir -p $HOME/android-sdk
            wget -q https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip -O $HOME/android-sdk/sdk-tools-linux.zip
            unzip -qq $HOME/android-sdk/sdk-tools-linux.zip -d $HOME/android-sdk
            echo "y" | $HOME/android-sdk/tools/bin/sdkmanager "platforms;android-30" "build-tools;30.0.3" "platform-tools"
            echo "export ANDROID_HOME=$HOME/android-sdk" >> $BASH_ENV
            echo "export PATH=$PATH:$HOME/android-sdk/tools:$HOME/android-sdk/tools/bin:$HOME/android-sdk/platform-tools" >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Check Java Version
          command: java -version
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: artifact-file